# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7aa0d8b7e6fd2a19386ba9f4398c7a19db5cf025fc88626fb6bdc10506e459337b08c68a0842946dd0453996c754625c589a9b3c38caad193bbf26838b5bbf1

test:
  secret_key_base: 2ae250e6ca71710571f4a088e07effffead50398d3f816794f18a817a76304fefec060d3bfdd5cc91777d154206963a3d8d48c201ca57512c3877fef1ac525a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
